{% set name = "fpdf" %}
{% set version = "1.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fpdf-{{ version }}.tar.gz
  sha256: 125840783289e7d12552b1e86ab692c37322e7a65b96a99e0ea86cca041b6779

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - fpdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reingart/pyfpdf
  summary: Simple PDF generation for Python
  license: LGPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL3
  description: |
    PyFPDF is a library for PDF document generation under Python, ported from PHP.
    Compared with other PDF libraries, PyFPDF is simple, small and versatile, with advanced capabilities, 
    and is easy to learn, extend and maintain.
  dev_url: https://github.com/reingart/pyfpdf
  doc_url: https://pyfpdf.readthedocs.io
extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
